version: '3'

services:
  app:
    image: streamlit-docker-2
    build:
      dockerfile: ./Dockerfile
      context: .
    environment: 
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app/